Create React App
IIC2513-2021-2/soundify-front pull request #1
Opened 2021-11-15 19:36 UTC by MFMG99

## Description

New React app with Soundify index page and scss styles.

## Requirements

Run `yarn install` to install node-sass@4.14.1 to use scss files.

## Additional changes

None

2021-11-15 22:01 UTC, meretamal requested changes
Muchas gracias 🙌 !! Tengo un par de comentarios

2021-11-15 22:01 UTC, meretamal commented on src/index.jsx
> +);
Centralizaría los componentes en App.jsx y acá solo llamaría a App y no a cada componente por separado

2021-11-15 23:03 UTC, sivicencio requested changes
En general bien. Dejé algunos comentarios para mejorar el estilo del código y algunas sugerencias y preguntas.

¿Podrías incluir también en la descripción del PR un screenshot del resultado, por favor?

2021-11-15 23:03 UTC, sivicencio commented on src/App.jsx
> +    </div>
Podríamos utilizar fragments para evitar un div aquí. Además, ¿por qué `Navbar` viene después si supuestamente es un header?
```suggestion
    <>
      <Navbar />
      <Cover />
    </>
```

2021-11-15 23:03 UTC, sivicencio commented on src/components/Cover.jsx
> +        <Pathways />
Indentación extra que puede eliminarse:
```suggestion
  return (
    <section class="cover">
      <h1>The most comprehensive artists catalogue</h1>
      <Pathways />
```

2021-11-15 23:03 UTC, sivicencio commented on src/components/Cover.jsx
> +    );
```suggestion
  );
```

2021-11-15 23:17 UTC, FranciscaOtero commented on src/App.jsx
> +      <Navbar />
Por el orden que esta acá la Navbar queda abajo de Cover, como se ve en la foto
<img width="1418" alt="Screen Shot 2021-11-15 at 20 02 30" src="https://user-images.githubusercontent.com/48388881/141866437-42c800e1-cfb3-4668-ab1d-d06f687c1442.png">
Es un detalle enano en verdad, pero ese orden se puede ver un poco confuso y tal vez sería mejor darlo vuelta para que la navbar quede arriba!

2021-11-15 23:19 UTC, FranciscaOtero commented on src/App.jsx
> +      <Navbar />
Chuta no había visto el comentario de @sivicencio, sorry jajaja

2021-11-15 23:31 UTC, MFMG99 commented on src/App.jsx
> +      <Navbar />
Sii! Cuando puse los componentes en la app puse la navbar abajo y no me di cuenta xd
Arreglado

2021-11-16 00:25 UTC, sivicencio approved these changes
Gracias por los cambios. Aunque queda un pequeño detalle aún, lo dejo aprobado desde ya para no bloquear el merge.

2021-11-16 00:25 UTC, sivicencio commented on src/styles/albums.scss
> +  }
Aún hay un pequeño detalle con la indentación. Lo seleccionado en este comentario debería estar 1 nivel más hacia la izquierda.

2021-11-16 00:27 UTC, meretamal approved these changes
Gracias por lo cambios ❤️

2021-11-16 01:45 UTC, merged