feat/uploadFiles
IIC2513-2021-2/soundify-front pull request #10
Opened 2021-11-25 16:31 UTC by pedroherreraj

## Description
This branch add the feature of uploading files. 3 views were created
- AlbumDetails.jsx
- AlbumEdit.jsx
- AlbumList.jsx
- AlbumNew.jsx

Also, the following components were created:
- CreateAlbum.jsx
- PatchAlbum.jsx

## Requirements
None

## Views
AlbumDetails view

![imagen](https://user-images.githubusercontent.com/62112123/143475620-6d410149-11da-440d-b039-c41cf43c39ac.png)

AlbumEdit view

![imagen](https://user-images.githubusercontent.com/62112123/143475657-51fb7fe0-2b09-4050-bffe-4eb5a20abe68.png)

AlbumList view

![imagen](https://user-images.githubusercontent.com/62112123/143476156-2106c039-19ec-418d-bc39-4fa13404da5e.png)

AlbumNew view

![imagen](https://user-images.githubusercontent.com/62112123/143476247-f216b256-415a-4263-bd35-ade1c763b081.png)

## Additional changes
App.jsx 
Add more routes

Albums.jsx
Little change to adapt it if its only one album

Navbar.jsx
Fix route

SingleAlbum.jsx
Little change to fix a error and to adapt it if its only one album

2021-11-25 21:19 UTC, valeeeriquelme requested changes

2021-11-25 21:19 UTC, valeeeriquelme commented on src/components/CreateAlbum.jsx
> +import config from '../config';
```suggestion

```

2021-11-25 21:19 UTC, valeeeriquelme commented on src/components/CreateAlbum.jsx
> +          return [];
```suggestion
          return response.text().then((message) => Promise.reject(new Error(message)));
```

2021-11-25 21:19 UTC, valeeeriquelme commented on src/components/CreateAlbum.jsx
> +          return [];
En la PR de manejo de sesión se dio esto mismo, podrías revisarla para tenerla de referencia. Creo que es mejor tratarlo así, para que sea manejado como un error y que no se siga con el "then".

2021-11-25 21:19 UTC, valeeeriquelme commented on src/components/PatchAlbum.jsx
> +    fetch(`${config.API_URL}/api/artists`)
```suggestion
    fetch(`${process.env.REACT_APP_API_URL`)
```

2021-11-25 21:19 UTC, valeeeriquelme commented on src/components/PatchAlbum.jsx
> +          return [];
Misma sugerencia que antes 
```suggestion
          return response.text().then((message) => Promise.reject(new Error(message)));
```

2021-11-25 21:19 UTC, valeeeriquelme commented on src/components/PatchAlbum.jsx
> +    fetch(`${config.API_URL}/api/albums/${id}`)
```suggestion
    fetch(`${process.env.REACT_APP_API_URL}/api/albums/${id}`)
```

2021-11-25 21:19 UTC, valeeeriquelme commented on src/components/PatchAlbum.jsx
> +          return [];
```suggestion
          return response.text().then((message) => Promise.reject(new Error(message)));
```

2021-11-25 21:19 UTC, valeeeriquelme commented on src/views/AlbumDetail.jsx
> +    fetch(`${config.API_URL}/api/albums/${id}`)
```suggestion
    fetch(`${process.env.REACT_APP_API_URL}/api/albums/${id}`)
```

2021-11-25 21:19 UTC, valeeeriquelme commented on src/views/AlbumDetail.jsx
> +import config from '../config';
```suggestion
```

2021-11-25 21:19 UTC, valeeeriquelme commented on src/components/PatchAlbum.jsx
> +import config from '../config';
```suggestion

```

2021-11-25 21:19 UTC, valeeeriquelme commented on src/views/AlbumDetail.jsx
> +          return null;
```suggestion
          return response.text().then((message) => Promise.reject(new Error(message)));
```

2021-11-25 21:19 UTC, valeeeriquelme commented on src/views/AlbumList.jsx
> +import config from '../config';
```suggestion
```

2021-11-25 21:19 UTC, valeeeriquelme commented on src/views/AlbumList.jsx
> +    fetch(`${config.API_URL}/api/albums`)
```suggestion
    fetch(`${process.env.REACT_APP_API_URL}/api/albums`)
```

2021-11-25 21:19 UTC, valeeeriquelme commented on src/views/AlbumList.jsx
> +          return [];
```suggestion
          eturn response.text().then((message) => Promise.reject(new Error(message)));
```

2021-11-25 21:19 UTC, valeeeriquelme commented on src/views/AlbumList.jsx
> +          <h2>Artists</h2>
¿No debería decir Albums?

2021-11-26 18:28 UTC, valeeeriquelme commented
Viendo el deploy de prueba, creo que faltaría cambiar el component 'Pathway', para que lleve a la ruta albumes

2021-11-26 22:56 UTC, sivicencio requested changes
Gracias por todos los cambios, pues básicamente agregaste toda la funcionalidad asociada a los álbumes. Dejé varios comentarios de cosas que se podrían hacer mejor y también algunos pequeños errores que encontré.

2021-11-26 22:56 UTC, sivicencio commented on src/views/AlbumList.jsx
> +    fetch(`${process.env.REACT_APP_API_URL}/api/albums`)
Vi que esto estaba como `config.API_URL` y que @valeeeriquelme sugirió un cambio. La verdad no sé cuál fue la razón, pero creo que si tenemos disponible un archivo de configuraciones, estaría bueno utilizarlo. Tal vez la sugerencia fue por consistencia con lo que ya estaba.

2021-11-26 22:56 UTC, sivicencio commented on src/components/CreateAlbum.jsx
> +/* eslint-disable max-len */
¿Es necesario deshabilitar esto, en vez de seguir lo que ESLint propone? Lo entiendo por la regla `jsx-a11y/label-has-associated-control`, que a veces puede ser difícil de solucionar, pero estas dos creo que sí se podrían respetar.

2021-11-26 22:56 UTC, sivicencio commented on src/components/CreateAlbum.jsx
> +              <label htmlFor="Artist">Artist:</label>
Creo que esto debería ser `artistId`:
```suggestion
              <label htmlFor="artistId">Artist:</label>
```

2021-11-26 22:56 UTC, sivicencio commented on src/components/CreateAlbum.jsx
> +                {artists.map((artist) => <option key={artist.name} value={artist.id}>{artist.name} </option>)}
Sería mejor utilizar el id como key:
```suggestion
                {artists.map((artist) => <option key={artist.id} value={artist.id}>{artist.name} </option>)}
```

2021-11-26 22:56 UTC, sivicencio commented on src/components/CreateAlbum.jsx
> +                <div>{errors.email}</div>
Hay un error con los nombres:
```suggestion
              {errors.publishedAt && touched.publishedAt && (
                <div>{errors.publishedAt}</div>
```

2021-11-26 22:56 UTC, sivicencio commented on src/components/PatchAlbum.jsx
> +/* eslint-disable max-len */
Mismo comentario sobre estas reglas que creo que deberían ser respetadas en lo posible.

2021-11-26 22:56 UTC, sivicencio commented on src/components/PatchAlbum.jsx
> +      .finally(() => setLoading(false));
Entiendo que estos dos `fetch` son independientes entre sí. Me parece que sería mejor intentar realizarlos con `Promise.all` para no interferir en estados compartidos, como por ejemplo `error` y `loading`. Con el código actual, podría suceder que no siempre los requests terminen en el mismo orden, y podría llegar a setearse un estado inconsistente por estar siendo compartidos. Con `Promise.all` se podría manejar de mejor manera los errores, retornando apenas se encuentre un error. Dejo el "comienzo" de mi propuesta:
```javascript
const requestPromises = [
  fetch(`${process.env.REACT_APP_API_URL}/api/artists`),
  fetch(`${process.env.REACT_APP_API_URL}/api/albums/${id}`)
];
Promise.all(requestPromises)
  .then(([artistsResponse, albumResponse]) => {
    if (!artistsResponse.ok) {
      // Set error state and return rejected promise
    }
    if (!albumResponse.ok) {
      // Set error state and return rejected promise
     }
     return Promise.all([artistsResponse.json(), albumResponse.json()])
  })
  .then(([artistsData, albumData]) => {
    // Use deserializers to set data
  })
  .catch(() => setError(true))
  .finally(() => setLoading(false));
  
```

2021-11-26 22:56 UTC, sivicencio commented on src/components/PatchAlbum.jsx
> +              <label htmlFor="Artist">Artist:</label>
```suggestion
              <label htmlFor="artistId">Artist:</label>
```

2021-11-26 22:56 UTC, sivicencio commented on src/components/PatchAlbum.jsx
> +                {artists.map((artist) => <option key={artist.name} value={artist.id}>{artist.name} </option>)}
```suggestion
                {artists.map((artist) => <option key={artist.id} value={artist.id}>{artist.name} </option>)}
```

2021-11-26 22:56 UTC, sivicencio commented on src/components/PatchAlbum.jsx
> +                <div>{errors.email}</div>
```suggestion
              {errors.publishedAt && touched.publishedAt && (
                <div>{errors.publishedAt}</div>
```

2021-11-26 22:56 UTC, sivicencio commented on src/components/PatchAlbum.jsx
> +        })}
Aquí falta `artistId`, ¿no?

2021-11-26 22:56 UTC, sivicencio commented on src/components/PatchAlbum.jsx
> +              />
¿Formik no incluye archivos en el componente `Field`?

2021-11-26 22:56 UTC, sivicencio commented on src/components/PatchAlbum.jsx
> +              <button type="submit">Patch album</button>
Creo que "Update album" es un texto más cercano al usuario común.

2021-11-26 22:56 UTC, sivicencio commented on src/components/PatchAlbum.jsx
> +            if (response.status !== 201) {
Este endpoint retorna `200`, por lo que debería ser:
```suggestion
            if (response.status !== 200) {
```

2021-11-26 22:56 UTC, sivicencio commented on src/components/PatchAlbum.jsx
> +            navigate(`/albums/${id}`);
Esto significa que aunque haya un error, se está redirigiendo al album. Creo que sería mejor dejar esto sólo para el caso exitoso.

2021-11-26 22:56 UTC, sivicencio commented on src/views/AlbumDetail.jsx
> +            <button onClick={() => navigate('edit')} type="button" className="button">Update</button>
Me parece que es mejor colocar "Edit" como texto del botón, ya que "Update" suele estar más asociado a cuando efectivamente se realizará la opción de actualizar, mientras que "Edit" se usa más para llevar al formulario de edición (como en este caso).

2021-11-26 23:13 UTC, valeeeriquelme commented on src/views/AlbumList.jsx
> +    fetch(`${process.env.REACT_APP_API_URL}/api/albums`)
Fue por consistencia más que nada, no me había percatado del config. En ese caso (de usar config), lo aplicaría para todos los casos en qué es usada la API URL.

2021-11-27 22:19 UTC, pedroherreraj commented on src/components/PatchAlbum.jsx
> +      .finally(() => setLoading(false));
Habia intentado hacerlo asi! Pero tuve unos errores implementadolo, asi que gracias!

2021-11-28 12:58 UTC, sivicencio approved these changes
Gracias por modificar el código con las sugerencias. Dejé 2 pequeñas cosas que surgieron de mi último review, sin embargo, lo dejo aprobado desde ya ✅

2021-11-28 12:58 UTC, sivicencio commented on src/components/CreateAlbum.jsx
> +                  </option>
Dos comentarios:
1. La key debería ser `artist.id` como sugerí en mi primer review
2. Hay un espacio extra después del nombre del artista, que creo que se puede eliminar
```suggestion
                  <option key={artist.id} value={artist.id}>
                    {artist.name}
                  </option>
```

2021-11-28 12:58 UTC, sivicencio commented on src/components/PatchAlbum.jsx
> +                  </option>
Hay un espacio extra después del nombre del artista, que creo que se puede eliminar
```suggestion
                  <option key={artist.id} value={artist.id}>
                    {artist.name}
                  </option>
```

2021-11-28 12:58 UTC, sivicencio commented on src/components/PatchAlbum.jsx
> +              />
Esta pregunta sigue pendiente, sin embargo, dejémoslo así no más, ya que es funcional.

2021-11-28 15:56 UTC, pedroherreraj commented on src/components/PatchAlbum.jsx
> +              />
No incluye! Busque por todos lados y la forma más óptima que pille es que esta escrita.

2021-11-28 15:56 UTC, pedroherreraj commented on src/components/CreateAlbum.jsx
> +                  </option>
Uuu se me paso esa key. Ahora lo arreglo

2021-11-28 16:03 UTC, merged