feat: add react router
IIC2513-2021-2/soundify-front pull request #2
Opened 2021-11-16 06:07 UTC by FranciscaOtero

## Description
React Router was installed to be able to navigate in the SPA. To be able to navigate,  4 files for views were created:
- ArtistDetail.jsx
- ArtisList.jsx
- Home.jsx
- NotFound.jsx

Also, the following components were created:
- Albums.jsx
- SingleAlbum.jsx

## Requirements
Run `yarn install` to install react-router-dom@6.

## Views
ArtistList view
![Screen Shot 2021-11-16 at 02 46 20](https://user-images.githubusercontent.com/48388881/141928868-624415e7-0898-4c96-8dee-910215dbe7b2.png)

ArtistDetail view
<img width="1409" alt="Screen Shot 2021-11-16 at 02 46 48" src="https://user-images.githubusercontent.com/48388881/141928951-733c1380-325b-4fd3-aae0-50cb3aea92f7.png">

## Additional changes
None

2021-11-16 14:55 UTC, dasolari reviewed
En general muy bien, esta todo claro. Deje un par de comentarios sobre arreglos mínimos y una sugerencia.

2021-11-16 14:55 UTC, dasolari commented on src/App.jsx
> +
Aquí creo que es necesario agregar indentación a todos esos componentes y borrar el espacio en blanco al final.

2021-11-16 14:55 UTC, dasolari commented on src/components/Albums.jsx
> +export default Albums;
Aquí falta una línea en blanco al final del archivo.

2021-11-16 14:55 UTC, dasolari commented on src/components/SingleAlbum.jsx
> +export default SingleAlbum;
Idem.

2021-11-16 14:55 UTC, dasolari commented on src/views/ArtistDetail.jsx
> +export default ArtistDetail;
Idem

2021-11-16 14:55 UTC, dasolari commented on src/views/ArtistList.jsx
> +export default ArtistList;
Idem.

2021-11-16 14:55 UTC, dasolari commented on src/views/NotFound.jsx
> +}
Idem.

2021-11-16 14:55 UTC, dasolari commented on src/views/ArtistDetail.jsx
> +
Aquí sobra un par de espacios en blanco.

2021-11-16 14:55 UTC, dasolari commented on src/views/Home.jsx
> +}
Dado que es un return de un solo componente, sugiero dejarlo así:
```suggestion
const Home = () => {
  return <Cover />;
}
```

2021-11-16 14:55 UTC, dasolari commented on src/views/ArtistDetail.jsx
> +const ArtistDetail = () => {
Creo que esta bien incluir componentes creados como función y con _arrow function_, así saben que hay más de una forma de crear componentes, pero explicaría bien que no es necesario que usen los dos en un proyecto, basta con que se decidan por uno.

2021-11-16 19:37 UTC, meretamal requested changes
Dejo un pequeño comentario

2021-11-16 19:37 UTC, meretamal commented on src/components/SingleAlbum.jsx
> +  const { album } = props;
Acá usaría _object destructuring_ para sacar los _props_, para dejar un código más limpio:
```suggestion
function SingleAlbum({ album }) {
```

2021-11-16 19:57 UTC, FranciscaOtero commented on src/components/SingleAlbum.jsx
> +  const { album } = props;
Oka!! Lo cambiare

2021-11-16 20:51 UTC, meretamal requested changes

2021-11-16 20:51 UTC, meretamal commented on src/views/ArtistDetail.jsx
> +        <button onClick={() => navigate(-1)} type="button" class="button">Back</button>
Me entró la duda ¿qué pasa si se presiona este botón y es la primera url que se vista de la página?

Creo que dejaría este botón para que navegue de manera explícita a `ArtistLists` (lo cual lo cambiaría a un `Link`)

2021-11-16 22:03 UTC, FranciscaOtero commented on src/views/ArtistDetail.jsx
> +        <button onClick={() => navigate(-1)} type="button" class="button">Back</button>
Vuelve al inicio del browser, como cuando abres una pestaña sin nada. Quería agregar lo de useNavigate para que sepan que existe, tal vez puedo mencionarlo pero no dejarlo en el código final

2021-11-17 02:26 UTC, sivicencio requested changes
Está súper la feature. Dejé varios comentarios, donde muchos son pequeños detalles en sintaxis y estilo de código. Eso sí, hay unos pocos que sí me parecen relevantes, como el esquema de URLs para artistas.

2021-11-17 02:26 UTC, sivicencio commented on src/components/Albums.jsx
> +      <ul class="albums">
Un pequeño detalle respecto al uso de clases en componentes React:
```suggestion
      <ul className="albums">
```

2021-11-17 02:26 UTC, sivicencio commented on src/components/SingleAlbum.jsx
> +      <img alt="album-cover-show" src={album.cover} />
Por temas de accesibilidad, podríamos utilizar un `alt` más descriptivo, como por ejemplo:
```suggestion
      <img alt={`${album.name}, album from ${album.artist}`} src={album.cover} />
```

2021-11-17 02:26 UTC, sivicencio commented on src/App.jsx
> +          <Route path="/artist/:id" element={<ArtistDetail/>} />
Y para seguir el esquema de rutas que hemos utilizado en la app web tradicional, sería bueno utilizar plurales (`artists` y `artists/:id`)

2021-11-17 02:26 UTC, sivicencio commented on src/components/Pathways.jsx
> +      <Link to='/artist'>Artists</Link>
Siguiendo mi comentario de plurales:
```suggestion
      <Link to='/artists'>Artists</Link>
```

2021-11-17 02:26 UTC, sivicencio commented on src/components/Navbar.jsx
> +              <Link to='/artist'>Artists</Link>
```suggestion
              <Link to='/artists'>Artists</Link>
```

2021-11-17 02:26 UTC, sivicencio commented on src/views/ArtistList.jsx
> +    <section class= 'container'>
```suggestion
    <section className='container'>
```

2021-11-17 02:26 UTC, sivicencio commented on src/views/ArtistList.jsx
> +      {artist.map((artist) => <div key={artist.id}><Link to={`/artist/${artist.id}`}>{`${artist.name}`}</Link></div>)}
Esto quedaría un poco más ordenado en varias líneas (sospecho que sería algo que ESLint atajaría, pero queda pendiente para otro PR configurarlo):
```suggestion
      {artist.map((artist) => (
        <div key={artist.id}>
          <Link to={`/artists/${artist.id}`}>{`${artist.name}`}</Link>
        </div>
      ))}
```

2021-11-17 02:26 UTC, sivicencio commented on src/views/ArtistDetail.jsx
> +    <section class= 'container'>
```suggestion
    <section className='container'>
```

2021-11-17 02:26 UTC, sivicencio commented on src/views/ArtistDetail.jsx
> +        <button onClick={() => navigate(-1)} type="button" class="button">Back</button>
Me parece interesante mostrar que existe `navigate`. Es lo que antes se lograba con `useHistory` y `history.push`. En general el uso que se le da es para llevar al usuario a cierta ruta luego de que ocurre alguna acción (por ejemplo, luego del submit de un formulario).

En este caso, a pesar de estar presente el caso borde que menciona Moisés, pienso que navegar a la página anterior tiene un comportamiento más cercano a una acción que el que tendría llevar a la lista de artistas (pues en este último caso esto se podría lograr con un link simplemente). Por lo tanto, tiendo a inclinarme por dejarlo como está. Eso sí, sería importante aclarar que hay más casos de uso para `navigate` que veremos en siguientes cápsulas que incluyan formularios.

2021-11-17 02:26 UTC, sivicencio commented on src/views/ArtistDetail.jsx
> +        <button onClick={() => navigate(-1)} type="button" class="button">Back</button>
```suggestion
        <button onClick={() => navigate(-1)} type="button" className="button">Back</button>
```

2021-11-17 02:26 UTC, sivicencio commented on src/views/Home.jsx
> +  return<Cover />;
```suggestion
  return <Cover />;
```

2021-11-17 02:26 UTC, sivicencio commented on src/views/NotFound.jsx
> +    <section class= 'container'>
```suggestion
    <section className='container'>
```

2021-11-17 18:21 UTC, sivicencio approved these changes
Súper, gracias por los cambios. Sólo falta un pequeño detalle que quedó de mi review original, sin embargo, lo dejo aprobado desde ya.

2021-11-17 18:21 UTC, sivicencio commented on src/views/ArtistList.jsx
> +    <section class= 'container'>
Falta actualizar este `className`.

2021-11-17 18:38 UTC, meretamal approved these changes

2021-11-17 18:51 UTC, merged