feat: add sesion persistence to front-end
IIC2513-2021-2/soundify-front pull request #7
Opened 2021-11-20 16:59 UTC by Pablok98

2021-11-22 01:53 UTC, valeeeriquelme commented
Agregaría una breve descripción al principio

2021-11-23 12:37 UTC, meretamal requested changes
Gracias @Pablok98, me quedan un par de dudas y comentarios

2021-11-23 12:37 UTC, meretamal commented on src/components/Cover.jsx
> +        {' '}
Si es que el usuario no inició sesión, se mostrarán dos espacios entre _welcome_ y el resto del texto.

2021-11-23 12:37 UTC, meretamal commented on .eslintrc.js
> +    'plugin:import/typescript',
¿Por qué se agregó este plugin, dado que no estamos usando typescript?

2021-11-23 12:37 UTC, meretamal commented on .eslintrc.js
> +        mjs: 'never',
Dado que no usamos este tipo de archivos, no los incluiría.

2021-11-23 12:37 UTC, meretamal commented on src/components/CreateArtist.jsx
> +
Cuando se haga _submit_ del formulario, se va a borrar todo el contenido de este para mostrar que está cargando. Usaría otro _approach_ para mostrar esto, cómo deshabilitando el botón y cambiando el texto

2021-11-23 14:33 UTC, dasolari requested changes
Deje un par de comentarios, entre estos hay uno que es necesario solucionar.

2021-11-23 14:33 UTC, dasolari commented on src/components/CreateArtist.jsx
> +    event.preventDefault();
Aquí faltó el `setLoading(true)`, dado que si no está, no se mostrará el el texto `Loading...`

2021-11-23 14:33 UTC, dasolari commented on src/components/CreateArtist.jsx
> +    event.preventDefault();
```suggestion
    setLoading(true);
    event.preventDefault();
```

2021-11-23 14:33 UTC, dasolari commented on src/contexts/AuthContext.jsx
> +    // eslint-disable-next-line react/jsx-no-constructed-context-values
El semestre pasado el lint no dió problemas con esto. Creo que sería mejor ver cuales son las diferencias en las configuraciones entre el linter de `Gudreads-front` y el de `soundify-front`, para que así no sea necesario usar este comentario.

2021-11-23 19:27 UTC, valeeeriquelme commented on src/components/Cover.jsx
> +        {' '}
Pensé lo mismo, pero revisé el preview y no pasa eso 🤔

2021-11-23 19:51 UTC, Pablok98 commented on src/components/Cover.jsx
> +        {' '}
Cacha que no, no estoy seguro por qué es el comportamiento, pero los espacios extra los elimina

2021-11-23 20:10 UTC, Pablok98 commented on src/components/CreateArtist.jsx
> +    event.preventDefault();
Esto está agregado, no sé por qué no se marca como outdated.

2021-11-23 20:21 UTC, Pablok98 commented on src/contexts/AuthContext.jsx
> +    // eslint-disable-next-line react/jsx-no-constructed-context-values
Está igual, no sé por qué me sale el error y antes no, quizás es nuevo en eslint?

2021-11-23 21:26 UTC, sivicencio requested changes
Puede que sea algo tarde, pero dejo mis comentarios luego del review. Coordinemos por interno a ver si se alcanzan a aplicar o no.

2021-11-23 21:26 UTC, sivicencio commented on src/views/ArtistList.jsx
> +          ) : <p>Log in to create a new artist</p>}
Para mantener el estilo de este operador ternario:
```suggestion
          ) : (
            <p>Log in to create a new artist</p>
          )}
```

2021-11-23 21:26 UTC, sivicencio commented on package.json
> +    "jsonwebtoken": "^8.5.1",
No estamos utilizando esta librería acá. Al quitarla hay que ejecutar `yarn install` para que se elimine del `yarn.lock` también.

2021-11-23 21:26 UTC, sivicencio commented on package.json
> +    "koa-jwt": "^4.0.3",
No estamos utilizando esta librería acá. Al quitarla hay que ejecutar `yarn install` para que se elimine del `yarn.lock` también.

2021-11-23 21:26 UTC, sivicencio commented on src/contexts/AuthContext.jsx
> +    clearSessionExpDate();
Si llamas a `handleUserLogout()` debería ser lo mismo, ¿no?

2021-11-23 21:26 UTC, sivicencio commented on src/components/CreateArtist.jsx
> +    [values],
Aquí me da la impresión de que faltaría `loading` en el array de dependencias.

2021-11-23 21:26 UTC, sivicencio commented on src/components/CreateArtist.jsx
> +        }
Esto haría que en caso de una respuesta "no ok" se devolviera `{}`, sin un error "real", lo que haría que se ejecute el siguiente `then` en la cadena, que utiliza `Deserializer` y llama a su vez a `addArtist`. O sea, estaríamos agregando un artista "vacío" a la lista de artistas.

Creo que sería mejor retornar `Promise.reject()` con algún mensaje de error, o bien, convertir todo esto a una versión con `await` (aprovechando que la función ya está marcada como async) y usar una estrategia similar al submit del login:
```suggestion
        if (!response.ok) {
          const error = await response.text();
          throw new Error(error);
        }
```

2021-11-23 21:42 UTC, Pablok98 commented on package.json
> +    "koa-jwt": "^4.0.3",
Se me pasaron, eso sí, la libreria jwt-decode si se está usando para obtener la expiración del acces_token.

2021-11-23 21:46 UTC, Pablok98 commented on src/components/CreateArtist.jsx
> +        }
No me permite utilizar el `await`, será porque está dentro del `fetch`?

2021-11-23 21:48 UTC, sivicencio commented on package.json
> +    "koa-jwt": "^4.0.3",
Sí, me refería sólo a `jsonwebtoken` y `koa-jwt`

2021-11-23 21:51 UTC, sivicencio commented on src/components/CreateArtist.jsx
> +        }
Claro, por eso decía que tendrías que convertir todo esto a una versión con `await`, desde `fetch`. Por eso tal vez sea más simple algo como:
```javascript
setError(true);
return Promise.reject('Something went wrong').
```
Lo único es que perderíamos el mensaje que viene desde la API. Alternativamente, se podría hacer algo como:
```javascript
setError(true);
return response.text().then((error) => Promise.reject('Something went wrong')).
```
No es lo más ordenado, pero permitiría acceder al error real desde la API, y que luego esté disponible en el `catch` siguiente en la cadena.

2021-11-23 22:06 UTC, Pablok98 commented on src/components/CreateArtist.jsx
> +        }
Ya que eslint solo deja rechazar por errores, quedaría así:

`return response.text().then((message) => Promise.reject(new Error(message)));`

(error como nombre de argumento era shadowname al error mismo)

2021-11-23 23:46 UTC, sivicencio commented on src/components/CreateArtist.jsx
> +        }
Yo creo que podemos dejarlo así. Debería entenderse.

2021-11-23 23:48 UTC, sivicencio approved these changes
Gracias por los cambios. Lo dejo aprobado sólo quedando pendiente lo de disponibilizar el error en `CreateArtist`.

2021-11-24 20:35 UTC, merged