Feat/testing react
IIC2513-2021-2/soundify-front pull request #9
Opened 2021-11-23 04:15 UTC by gonzaloconcha

Se agregan 3 tests para la vista de "artists" usando react-testing-library y MSW (mocking service worker) para simular una API.
Se instaló el paquete de MSW usando `yarn add msw --dev` por lo que se requiere instalar las dependencias.
Se modificó `App.jsx` y se crea `AppRouter.jsx` el cual se utiliza para realizar los tests.

2021-11-24 22:09 UTC, valeeeriquelme requested changes

2021-11-24 22:09 UTC, valeeeriquelme commented on src/AppRoutes.jsx
> +        <Route path="/login" element={<Login />} />
Falta el path a register

2021-11-24 22:11 UTC, valeeeriquelme requested changes

2021-11-24 22:11 UTC, valeeeriquelme commented on src/App.jsx
> -import Register from './views/Register';
En AppRoutes hay que agregar este import

2021-11-24 23:57 UTC, sivicencio requested changes
Bien en general. Dejé algunos cambios relativos a reorganización del código.

2021-11-24 23:57 UTC, sivicencio commented on src/App.jsx
> +      </main>
Este cambio está alterando la estructura que teníamos previamente. No sé si afectará en el estilo, pero lo que sí ocurre es que `<main</main>` encierra todo ahora, incluso el header (en `<NavBar />`) y no debería, pues el header es independiente de main.

Deberíamos mantener la estructura original, es decir algo como lo siguiente:
```suggestion
      <AppRoutes />
```
Y que `<AppRoutes />` incluya todo lo original, desde `<AuthContextProvider>` como componente que encierra todo, pasando con `Navbar` y `main` como hijos, y luego `<Routes>` dentro de `main`.

2021-11-24 23:57 UTC, sivicencio commented on src/AppRoutes.jsx
> +      <Routes>
Como mencioné previamente, este `<Routes>` debería estar encerrado por un `<main>`.

2021-11-24 23:57 UTC, sivicencio commented on src/AppRoutes.jsx
> +
Esta línea se puede eliminar.
```suggestion
```

2021-11-24 23:57 UTC, sivicencio commented on src/views/ArtistList.test.jsx
> +};
Este objeto, que luego se utiliza para el mock de `localStorage.getItem` no está considerando la key `sessionExpiration`, que se utiliza para cerrarle la sesión a un usuario de forma automática. En este caso particular no afecta por la forma en que está construido el logout automático (que sólo se "activa" si existe un valor asociado a la key `sessionExpiration` de `localStorage`). Sin embargo, no se está realmente testeando el caso real donde un usuario podría quedar deslogueado si expiró el JWT (es por eso que si revisas la cápsula pasada, verás que se construye para que siempre sea un día en el futuro (y, por lo tanto, no haya expirado aún)).

Creo que para acercarnos lo más posible al caso real, deberíamos agregar ese comportamiento.

2021-11-24 23:57 UTC, sivicencio commented on src/views/ArtistList.test.jsx
> +      const logginMessage = screen.getByText(/Log in to create a new artist/i);
```suggestion
      const loginMessage = screen.getByText(/Log in to create a new artist/i);
```

2021-11-24 23:57 UTC, sivicencio commented on src/views/ArtistList.test.jsx
> +    it('renders the artist list data', async () => {
Esto podrías dividirlo en dos tests, pues en los expects hay cosas diferentes:
- Uno que testee que se renderea la data de los artistas (donde puedes mantener la descripción)
- Otro donde se testee que se muestra el login message

Y toda la lógica común puedes agruparla en un `beforeAll`

2021-11-24 23:57 UTC, sivicencio commented on src/views/ArtistList.test.jsx
> +      expect(logginMessage).not.toBeInTheDocument();
Lo mismo que en el caso del usuario no logueado en cuanto a dividir estos tests en uno que testee la data, y otro que testee que en este caso no aparece el login message.

2021-11-24 23:57 UTC, sivicencio commented on src/views/ArtistList.test.jsx
> +      const logginMessage = screen.queryByText(/Log in to create a new artist/i);
```suggestion
      const loginMessage = screen.queryByText(/Log in to create a new artist/i);
```

2021-11-25 00:54 UTC, gonzaloconcha commented on src/AppRoutes.jsx
> +
Traté pero falla al compilar

2021-11-25 02:52 UTC, merged